### ISSUE TITLE
 [L4T r24.2.1]

### ISSUE THREAD

**Issue by aysegulucar2016** [jetsonhacks/buildJetsonFTDIModule#2]
Can we use buildJetsonFTDIModule after L4T r24.2.1, that is jetpack 3.0,  install too?
(It means that the current version is for L4T 21.5)

**Comment by jetsonhacks** [comment]
Not quite sure what you are asking. This repository is for Jetson TK1. The latest OS for TK1 is L4T 21.5, it is installed by JetPack 2.3+. This is for L4T 21.5.

L4T 24.2.1 is for the Jetson **TX1**, not the TK1.

**Comment by aysegulucar2016** [comment]
Thanks for answer. It is corrrect. I am looking for one for tx1.
